image: node:8.9.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
            - firebase-hosting
          script:
            - yarn install
            - yarn deploy

definitions:
  caches:
    firebase-hosting: .firebase
